# Generated by Django 2.0.7 on 2018-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Genere', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='./image/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(upload_to='./mp3/320/')),
                ('lyrics', models.FileField(upload_to='./lyrics/%Y/%m/%d/')),
                ('upload_128', models.FileField(upload_to='./mp3/128/')),
                ('upload_192', models.FileField(upload_to='./mp3/192/')),
            ],
        ),
    ]
