# Generated by Django 2.0.7 on 2018-10-15 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(null=True, upload_to='./image/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.FileField(null=True, upload_to='./lyrics/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['lrc'])]),
        ),
        migrations.AlterField(
            model_name='music',
            name='upload',
            field=models.FileField(null=True, upload_to='./mp3/320/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
