# Generated by Django 2.0.7 on 2018-08-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='name',
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='Genere',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='image',
            field=models.ImageField(default=1, upload_to='image/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='upload',
            field=models.FileField(default=1, upload_to='mp3/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
