# Generated by Django 2.0.7 on 2018-10-17 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181016_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(default='/app/media/placeholder.png', upload_to='./image/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.FileField(default='/app/media/Adele_-_Hello.lrc', null=True, upload_to='./lyrics/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['lrc'])]),
        ),
    ]
