# Generated by Django 2.0.7 on 2018-10-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181017_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='upload_128',
            field=models.FileField(blank=True, null=True, upload_to='./mp3/128/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='upload_192',
            field=models.FileField(blank=True, null=True, upload_to='./mp3/192/'),
        ),
    ]
