# Generated by Django 2.0.7 on 2018-10-17 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181017_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.FileField(default='/app/media/Adele_-_Hello.lrc', upload_to='./lyrics/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['lrc'])]),
        ),
    ]
