# Generated by Django 2.0.7 on 2018-10-17 15:14

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181017_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(default='/app/media/placeholder.png', upload_to='./image/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.FileField(default='/app/media/Adele_-_Hello.lrc', upload_to='./lyrics/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['lrc']), api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='music',
            name='upload',
            field=models.FileField(upload_to='./mp3/320/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3']), api.validators.validate_file_size]),
        ),
    ]
